web:
    build: .
    links:
        - 'db'
    ports:
        - '80:8000'
    environment:
        - 'DATABASE_HOST=db'
        - 'DATABASE_NAME=postgres'
        - 'DATABASE_USER=postgres'
        - 'DATABASE_PASSWORD=postgres'
db:
    image: postgres:9.4
    ports:
        - '5432:5432'
